### ISSUE TITLE
Advice on WRFextraction problem

### ISSUE THREAD

**Issue by gaoxiangand** [Zhang-Zhaoyu/WRF-SOWFA_Coupling#1]
Sorry to bother you, but I would like to know how to get the points (x,y,z) on each boundary and convert x,y,z to lat/lon/elev to get _bc.dat？I tried the program, but it never worked. If you have a program, please show it to me.

**Comment by Zhang-Zhaoyu** [comment]
Hi! The points (x,y,z) are coordinates of boundary surfaces from SOWFA domain. Then, transfer the local coordinate (x,y,z) to global (lat/lon/elevation) based on the location where you want to simulate. One more important point, you should make sure that you have compiled the tool successfully. There are some code that should be edited depending on your SOWFA version (you possibly have seen some of answers about that on SOWFA github). Hope it can help.

**Comment by gaoxiangand** [comment]
Hi, I should have compiled successfully, the result is the same as on Gtihub. Now the strange thing is that I can generate data for north and South, but the other ones like east and upper report an error: opening: FLNM (I) 1 WRfout_d01_2000-01-24_16:00:00

Dimensions: 1 50 1 50 1 50

Reading latitude/longitude from latlong.nc

The WRF grid is blessings approx. -0.00000 deg. From true Lat /lon.

Getting variables from solution file

Have heat flux: T

Processing body 1 : west_bc.dat

Precomputing points for body 1



Program received signal SIGSEGV: Segmentation fault - invalid memory reference.



Backtrace for this error:

#0 0x7efd5e8952ed in ???

#1 0x7efd5e894503 in ???

#2 0x7efd5e129f0f in ???

#3 0x55754b1f1ab7 in ???

#4 0x55754b1e76be in ???

#5 0x7efd5e10cc86 in ???

#6 0x55754b1e76f9 in ???

#7 0xffffffffffffffff in ???

Segmentation fault (core dumped)

Is there a problem with _BC.dat that I extracted?
And the wind speed I'm generating seems a little high：
 2401
(
(  -9.2212420  171.4160461  -22.0147266)
(  -9.8170252  171.0000916  -22.4817944)
(  -9.8208475  171.0991364  -22.4944820)
(  -9.8243227  171.1891937  -22.5060177)
(  -9.8281460  171.2882385  -22.5187073)
( -10.4255114  170.8709412  -22.9869881)
( -10.4292908  170.9607239  -22.9987583)
( -10.4334488  171.0594940  -23.0117035)
( -10.4372282  171.1492920  -23.0234737)
( -10.4413853  171.2480621  -23.0364189)
( -11.0406389  170.8291473  -23.5061474)
( -11.0451307  170.9276276  -23.5193520)
( -11.0492144  171.0171509  -23.5313530)
( -11.0532990  171.1066895  -23.5433559)
( -11.0577908  171.2051697  -23.5565586)
( -11.0618744  171.2946930  -23.5685616)
( -11.0663671  171.3931732  -23.5817642)
( -11.6681461  170.9721222  -24.0534325)
( -11.6729736  171.0703125  -24.0668926)
( -11.6773615  171.1595764  -24.0791283)
( -11.6817493  171.2488556  -24.0913658)
( -11.6865768  171.3470459  -24.1048260)
( -11.6909647  171.4363251  -24.1170616)
( -11.6957922  171.5345154  -24.1305218)

**Comment by Zhang-Zhaoyu** [comment]
If the tool has successfully compiled, the most possible issue usually comes from the input file. Does the _BC.dat fit the WRF output? Because -24 for the elevation is a little bit strange. You could change the _BC.dat to a single point which is contained by WRFoutput certainty and then check the result.

**Comment by gaoxiangand** [comment]
Hello, thank you very much for your answer.

when I use *_bc.dat input, and (./wrftoof wrfout_d03_2000-01-25_12:00:00 -startdate 2000-01-25_12_00_00-offset 2000) command to extract the speed of each boundary, the reason is all negative, as shown in the following（north/2000/U）.And it ran without error.

10201
(
( -6.5704446 -5.0668082 -0.0196759)
( -6.5419059 -4.9812737 -0.0197884)
( -6.5419059 -4.9812737 -0.0197884)
( -6.5419059 -4.9812737 -0.0197884)
( -6.5133672 -4.8957396 -0.0199009)
( -6.4757080 -4.8093982 -0.0208689)
( -6.4757080 -4.8093982 -0.0208689)
( -6.4411683 -4.7315555 -0.0218498)
( -6.4411683 -4.7315555 -0.0218498)
( -6.4411683 -4.7315555 -0.0218498)
So I want to ask, what could be the cause of this phenomenon?

**Comment by gaoshijingand** [comment]
hello
I have two questions about the wrftoof code:

After successfully extracting data at each boundary using WRFextraction, I find that the extracted velocity U is always negative, as shown in the figure below. I would like to ask whether this phenomenon is normal?
![3(PS4E){ J27%QX $9R_E)J](https://user-images.githubusercontent.com/119996931/207504739-7a28b0e2-13e4-4d32-affc-b5d36b0e9de0.png)


When I use the command./wrftoof wrfout_d03_2000-01-25_12:00:00 -startdate 2000-01-25_12: 00:00-offset 0
I tried to extract data with different offsets, but I found that the data I extracted were all the same. So I would like to ask if a wrfout can only extract the data of one moment in time. With offset you can just change the name of the output folder.

**Comment by wineallergy** [comment]
> Hello, thank you very much for your answer.
> 
> when I use *_bc.dat input, and (./wrftoof wrfout_d03_2000-01-25_12:00:00 -startdate 2000-01-25_12_00_00-offset 2000) command to extract the speed of each boundary, the reason is all negative, as shown in the following（north/2000/U）.And it ran without error.
> 
> 10201 ( ( -6.5704446 -5.0668082 -0.0196759) ( -6.5419059 -4.9812737 -0.0197884) ( -6.5419059 -4.9812737 -0.0197884) ( -6.5419059 -4.9812737 -0.0197884) ( -6.5133672 -4.8957396 -0.0199009) ( -6.4757080 -4.8093982 -0.0208689) ( -6.4757080 -4.8093982 -0.0208689) ( -6.4411683 -4.7315555 -0.0218498) ( -6.4411683 -4.7315555 -0.0218498) ( -6.4411683 -4.7315555 -0.0218498) So I want to ask, what could be the cause of this phenomenon?

Hello,sorry to bother you. Now I have successfully compiled wrtoof.Now I have the same question that you have worked it out.I know that I need to provide *_bc.dat as the input of wrtoof.But I really do  not know how to  extract the lat/lon/elevation and gengerate  *_bc.dat file. Which program do I need to use？I am realyly confused.I know you work it out. So could please told me how to do it. Thank you very much. Best wishes for you.
